<?php

namespace Shop\ShopBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository {

    public function getName($id) {
        
        $qb = $this -> createQueryBuilder('c')
                    ->select('c')
                    -> where ('c.id = :category_id')
                    -> setParameter('category_id', $id);
        
        
        return $qb->getQuery()->getResult();
    }

}
